### ISSUE TITLE
PXD-552 ⁃ DCF -> ISB -> Index TCGA staging bucket

### ISSUE THREAD

**Issue by gneglur** [uc-cdis/indexd#130]
We need to index the following 2 TCGA buckets on DCF staging:
https://nci-crdc-staging.datacommons.io

1) gdc-tcga-phs000178-open-staging
Created under Google Project: dcf-staging-202214
allAuthenticatedUsers have Storage Object Viewer role
2) gdc-tcga-phs000178-controlled-staging
Created under Google Project: dcf-staging-202214
isb-cgc-test-cntl@isb-cgc.org has Storage Object Viewer role
group_tcga-dbgap-authorized@firecloud.org has Storage Object Viewer role

**Comment by trevars** [comment]
Need a manifest from ISB before indexing can be done.

**Comment by gneglur** [comment]
@frickjack - what should the manifest look like? (format/content) - can you provide more details so I can follow-up with ISB.

**Comment by philloooo** [comment]
isb has provided the manifest with mapping from gdc did to object store uri.
We can index them by:
```
gdc_endpoint = 'https://api.gdc.cancer.gov/files/{gdc_id}'
for (gdc_id, path) in manifest:
  if path.startswith('gs://gdc-tcga-phs000178-open-staging'):
    acl = ['*']
  else:
    acl = ['phs000178']
  size, md5 = get_info(gdc_endpoint, gdc_id)
upsert_indexd(did=gdc_id, acl=acl, size=size, md5=md5)
```

**Comment by frickjack** [comment]
manifest is here: https://docs.google.com/spreadsheets/d/1A8lQ17JnYQOfATX6wOaivL4t_l5O33mKSIy6mGKN6Xc/edit#gid=0

**Comment by philloooo** [comment]
➤ Reuben Pasquini commented:

manifest is here: https://docs.google.com/spreadsheets/d/1A8lQ17JnYQOfATX6wOaivL4t_l5O33mKSIy6mGKN6Xc/edit#gid=0
