### ISSUE TITLE
PXD-822 ⁃ Add possibility to query indexd with a negated param

### ISSUE THREAD

**Issue by khan08** [uc-cdis/indexd#137]
When getting indexes, introduce a negate operation. With indexclient, add a new parameter in list_with_parms() called negate_params, all the values passed in negate_params will be negated (not equal or not exist)

Below is an example:
```
docs = self.index_client.list_with_params(
            params=
               {'acl': ['open']
                'urls_metadata': {
                    's3://amazonaws.com/': {
                    'state': ''validated"
                },
            negate_params=
               {'acl': ['example']
                'urls_metadata': {
                   's3://example.com/': None
                }
               }})
```
This will return all records that:
- have acl open
- urls_metadata have [<key like '%s3://amazonaws.com%'>]['state'] == validated,
- don't have acl example
- urls_metadata don't have key like '%s3://example.com%'

Different level of negation
For negate params, urls_metadata and metadata can have different level of negation. If passed (key, value) has (NOT value is True), then filter by NOT exist key.

Below will exclude all records that have urls_metadata with url_key LIKE '%s3://example.com%'
```
{
  'urls_metadata': {
    's3://example.com/': None
  }
}
```
Below will exclude all records that have key "state" in urls_metadata[<key like'%s3://example.com%'>]
```
{
  'urls_metadata': {
    's3://example.com/': {'state': None}
  }
}
```
Below will exclude all records with state "validated" in urls_metadata[<key like'%s3://example.com%'>]['state']
```
{
  'urls_metadata': {
    's3://example.com/': {'state': 'validated'}
  }
}
```

**Comment by zflamig** [comment]
Completed in #138
