### ISSUE TITLE
PXD-1134 ⁃ Implement updated DOS list request

### ISSUE THREAD

**Issue by david4096** [uc-cdis/indexd#146]
DOS moved from POST to GET on its list endpoint. This issue is meant to track the necessary changes to update indexd to support the new version.

Server changes here https://github.com/uc-cdis/indexd/blob/master/indexd/dos/blueprint.py

Add client tests here https://github.com/uc-cdis/indexd/blob/master/tests/test_client.py#L624

Pull request at DOS with schema change https://github.com/ga4gh/data-object-service-schemas/pull/87

**Comment by natanlao** [comment]
Tracking this as [TLP-387](https://ucsc-cgl.atlassian.net/browse/TLP-387) as well
