### ISSUE TITLE
indexd index_record 'size' field need to be BIGINT

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/indexd#56]
If we want to continue storing file size in bytes, then we need to update our schema:

class IndexRecord(Base):
    '''
    Base index record representation.
    '''
    __tablename__ = 'index_record'

    did = Column(String, primary_key=True)
    rev = Column(String)
    form = Column(String)
    size = Column(Integer)

------------
https://www.postgresql.org/docs/9.1/static/datatype-numeric.html

**Comment by zflamig** [comment]
Resolved in #60
