### ISSUE TITLE
Indexd crash bug

### ISSUE THREAD

**Issue by phuongph** [uc-cdis/indexd#71]
**Here is what happen:**

- Indexclient uses the wrong user/password to access Indexd server.

-  The client can still query the data.

- However, if the client updates or creates new entries, and does it in a loop (let say 100 times, or 1000 times) with fast speed (a couple of milliseconds per request).

- Indexd returns request errors for sometimes.

- And crashes

**Comment by philloooo** [comment]
wasn't able to reproduce it in our dev cluster
```
for i in {1..1000}; do curl https://dev.bionimbus.org/index/index/ -XPOST >>index.log 2>/dev/null & done
```
works fine for me?

**Comment by phuongph** [comment]
I was not able to regenerate it either - will take a look at `indexd-populator` to see what happen 2 months ago.
