### ISSUE TITLE
500 Errors

### ISSUE THREAD

**Issue by zflamig** [uc-cdis/indexd#87]
[Thu Mar 15 16:07:37.785181 2018] [wsgi:error] [pid 18:tid 140064201840384] Traceback (most recent call last):
[Thu Mar 15 16:07:37.785184 2018] [wsgi:error] [pid 18:tid 140064201840384]   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
[Thu Mar 15 16:07:37.785185 2018] [wsgi:error] [pid 18:tid 140064201840384]     response = self.full_dispatch_request()
[Thu Mar 15 16:07:37.785187 2018] [wsgi:error] [pid 18:tid 140064201840384]   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
[Thu Mar 15 16:07:37.785189 2018] [wsgi:error] [pid 18:tid 140064201840384]     rv = self.handle_user_exception(e)
[Thu Mar 15 16:07:37.785191 2018] [wsgi:error] [pid 18:tid 140064201840384]   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
[Thu Mar 15 16:07:37.785193 2018] [wsgi:error] [pid 18:tid 140064201840384]     reraise(exc_type, exc_value, tb)
[Thu Mar 15 16:07:37.785194 2018] [wsgi:error] [pid 18:tid 140064201840384]   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
[Thu Mar 15 16:07:37.785195 2018] [wsgi:error] [pid 18:tid 140064201840384]     rv = self.dispatch_request()
[Thu Mar 15 16:07:37.785197 2018] [wsgi:error] [pid 18:tid 140064201840384]   File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
[Thu Mar 15 16:07:37.785198 2018] [wsgi:error] [pid 18:tid 140064201840384]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Mar 15 16:07:37.785200 2018] [wsgi:error] [pid 18:tid 140064201840384]   File "/usr/local/lib/python2.7/dist-packages/indexd-0.1-py2.7.egg/indexd/auth/__init__.py", line 24, in check_auth
[Thu Mar 15 16:07:37.785201 2018] [wsgi:error] [pid 18:tid 140064201840384]     return f(*args, **kwargs)
[Thu Mar 15 16:07:37.785202 2018] [wsgi:error] [pid 18:tid 140064201840384]   File "/usr/local/lib/python2.7/dist-packages/indexd-0.1-py2.7.egg/indexd/index/blueprint.py", line 264, in add_index_record_version
[Thu Mar 15 16:07:37.785204 2018] [wsgi:error] [pid 18:tid 140064201840384]     form = flask.request.json['form']
[Thu Mar 15 16:07:37.785205 2018] [wsgi:error] [pid 18:tid 140064201840384] KeyError: 'form'

**Comment by philloooo** [comment]
resolved by a previous pr
