### ISSUE TITLE
Allow lookups by baseid

### ISSUE THREAD

**Issue by dankolbman** [uc-cdis/indexd#89]
It seems that it is currently not possible to try and resolve a document given only a baseid. These seems like it should be possible.

A suggested implementation may either be to:
1) Use the existing `/index/{UUID}` endpoints to also return `BaseVersion` documents
2) Implement a new resource to resolve base uuids like `/base/{UUID}`

**Comment by philloooo** [comment]
do you want to use the baseid to retrieve all the documents or the latest document?

**Comment by dankolbman** [comment]
That's a design decision that's up to you. Either would be functionally equivalent to me.
Perhaps `/index/{UUID}` should stay consistent and return that document, when `UUID=did`, and return the latest document when `UUID=baseid`
